# Generated by Django 3.2.9 on 2024-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_value', models.CharField(max_length=500)),
                ('block_hashes', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('l2_verification_link', models.CharField(max_length=5000)),
            ],
        ),
    ]
