# Generated by Django 3.2.9 on 2024-11-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcomapp', '0002_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
