# Generated by Django 3.2.9 on 2024-11-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcomapp', '0003_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='l2_verification_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
